FROM node:16.20.2-alpine


WORKDIR /app
ENV NODE_ENV=development
COPY backend/package.json backend/yarn.lock ./
RUN yarn install

COPY ./backend ./
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start:dev" ]